name: portal_sirs
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  shrink_sidemenu: ^2.0.0+2-null-safety
  sliver_app_bar_builder: ^1.1.0
  dio: ^5.3.3
  hexcolor: ^3.0.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
    - assets/logo/
    - assets/images/
    - assets/design_course/

